# favor zram-backed swapping over OOM on small boards
vm.swappiness = 80
vm.watermark_boost_factor = 0
fs.protected_symlinks = 1
fs.protected_hardlinks = 1
kernel.unprivileged_bpf_disabled = 1
net.core.bpf_jit_harden = 2
